interface Country {
  code: string;
  name: string;
  nationality: string;
  flag: string;
  callingCode: string;
}

export const countries: Country[] = [
  {
    code: "AFG",
    name: "Afghanistan",
    nationality: "Afghanistanian",
    flag: "🇦🇫",
    callingCode: "+93",
  },
  {
    code: "ALB",
    name: "Albania",
    nationality: "Albanian",
    flag: "🇦🇱",
    callingCode: "+355",
  },
  {
    code: "DZA",
    name: "Algeria",
    nationality: "Algerian",
    flag: "🇩🇿",
    callingCode: "+213",
  },
  {
    code: "AND",
    name: "Andorra",
    nationality: "Andorran",
    flag: "🇦🇩",
    callingCode: "+376",
  },
  {
    code: "AGO",
    name: "Angola",
    nationality: "Angolan",
    flag: "🇦🇴",
    callingCode: "+244",
  },
  {
    code: "ARG",
    name: "Argentina",
    nationality: "Argentinan",
    flag: "🇦🇷",
    callingCode: "+54",
  },
  {
    code: "ARM",
    name: "Armenia",
    nationality: "Armenian",
    flag: "🇦🇲",
    callingCode: "+374",
  },
  {
    code: "AUS",
    name: "Australia",
    nationality: "Australian",
    flag: "🇦🇺",
    callingCode: "+61",
  },
  {
    code: "AUT",
    name: "Austria",
    nationality: "Austrian",
    flag: "🇦🇹",
    callingCode: "+43",
  },
  {
    code: "AZE",
    name: "Azerbaijan",
    nationality: "Azerbaijanian",
    flag: "🇦🇿",
    callingCode: "+994",
  },

  {
    code: "BHS",
    name: "Bahamas",
    nationality: "Bahamasian",
    flag: "🇧🇸",
    callingCode: "+1242",
  },
  {
    code: "BHR",
    name: "Bahrain",
    nationality: "Bahrainian",
    flag: "🇧🇭",
    callingCode: "+973",
  },
  {
    code: "BGD",
    name: "Bangladesh",
    nationality: "Bangladeshian",
    flag: "🇧🇩",
    callingCode: "+880",
  },
  {
    code: "BRB",
    name: "Barbados",
    nationality: "Barbadosian",
    flag: "🇧🇧",
    callingCode: "+1246",
  },
  {
    code: "BLR",
    name: "Belarus",
    nationality: "Belarusian",
    flag: "🇧🇾",
    callingCode: "+375",
  },
  {
    code: "BEL",
    name: "Belgium",
    nationality: "Belgiumian",
    flag: "🇧🇪",
    callingCode: "+32",
  },
  {
    code: "BLZ",
    name: "Belize",
    nationality: "Belizean",
    flag: "🇧🇿",
    callingCode: "+501",
  },
  {
    code: "BEN",
    name: "Benin",
    nationality: "Beninian",
    flag: "🇧🇯",
    callingCode: "+229",
  },
  {
    code: "BTN",
    name: "Bhutan",
    nationality: "Bhutanian",
    flag: "🇧🇹",
    callingCode: "+975",
  },
  {
    code: "BOL",
    name: "Bolivia",
    nationality: "Bolivian",
    flag: "🇧🇴",
    callingCode: "+591",
  },
  {
    code: "BIH",
    name: "Bosnia and Herzegovina",
    nationality: "Bosnian",
    flag: "🇧🇦",
    callingCode: "+387",
  },
  {
    code: "BWA",
    name: "Botswana",
    nationality: "Botswanan",
    flag: "🇧🇼",
    callingCode: "+267",
  },
  {
    code: "BRA",
    name: "Brazil",
    nationality: "Brazilian",
    flag: "🇧🇷",
    callingCode: "+55",
  },
  {
    code: "BRN",
    name: "Brunei",
    nationality: "Bruneiian",
    flag: "🇧🇳",
    callingCode: "+673",
  },
  {
    code: "BGR",
    name: "Bulgaria",
    nationality: "Bulgarian",
    flag: "🇧🇬",
    callingCode: "+359",
  },
  {
    code: "BFA",
    name: "Burkina Faso",
    nationality: "Burkina Fasoian",
    flag: "🇧🇫",
    callingCode: "+226",
  },
  {
    code: "BDI",
    name: "Burundi",
    nationality: "Burundiian",
    flag: "🇧🇮",
    callingCode: "+257",
  },

  {
    code: "CAN",
    name: "Canada",
    nationality: "Canadan",
    flag: "🇨🇦",
    callingCode: "+1",
  },
  {
    code: "CHN",
    name: "China",
    nationality: "Chinan",
    flag: "🇨🇳",
    callingCode: "+86",
  },
  {
    code: "COL",
    name: "Colombia",
    nationality: "Colombian",
    flag: "🇨🇴",
    callingCode: "+57",
  },
  {
    code: "CRI",
    name: "Costa Rica",
    nationality: "Costa Rican",
    flag: "🇨🇷",
    callingCode: "+506",
  },
  {
    code: "HRV",
    name: "Croatia",
    nationality: "Croatian",
    flag: "🇭🇷",
    callingCode: "+385",
  },
  {
    code: "CUB",
    name: "Cuba",
    nationality: "Cuban",
    flag: "🇨🇺",
    callingCode: "+53",
  },
  {
    code: "CZE",
    name: "Czech Republic",
    nationality: "Czech",
    flag: "🇨🇿",
    callingCode: "+420",
  },

  {
    code: "DNK",
    name: "Denmark",
    nationality: "Denmarkian",
    flag: "🇩🇰",
    callingCode: "+45",
  },
  {
    code: "EGY",
    name: "Egypt",
    nationality: "Egyptian",
    flag: "🇪🇬",
    callingCode: "+20",
  },
  {
    code: "ETH",
    name: "Ethiopia",
    nationality: "Ethiopian",
    flag: "🇪🇹",
    callingCode: "+251",
  },

  {
    code: "FIN",
    name: "Finland",
    nationality: "Finnish",
    flag: "🇫🇮",
    callingCode: "+358",
  },
  {
    code: "FRA",
    name: "France",
    nationality: "French",
    flag: "🇫🇷",
    callingCode: "+33",
  },

  {
    code: "DEU",
    name: "Germany",
    nationality: "German",
    flag: "🇩🇪",
    callingCode: "+49",
  },
  {
    code: "GRC",
    name: "Greece",
    nationality: "Greek",
    flag: "🇬🇷",
    callingCode: "+30",
  },

  {
    code: "HUN",
    name: "Hungary",
    nationality: "Hungarian",
    flag: "🇭🇺",
    callingCode: "+36",
  },
  {
    code: "ISL",
    name: "Iceland",
    nationality: "Icelandic",
    flag: "🇮🇸",
    callingCode: "+354",
  },
  {
    code: "IND",
    name: "India",
    nationality: "Indian",
    flag: "🇮🇳",
    callingCode: "+91",
  },
  {
    code: "IDN",
    name: "Indonesia",
    nationality: "Indonesian",
    flag: "🇮🇩",
    callingCode: "+62",
  },
  {
    code: "IRL",
    name: "Ireland",
    nationality: "Irish",
    flag: "🇮🇪",
    callingCode: "+353",
  },
  {
    code: "ISR",
    name: "Israel",
    nationality: "Israeli",
    flag: "🇮🇱",
    callingCode: "+972",
  },
  {
    code: "ITA",
    name: "Italy",
    nationality: "Italian",
    flag: "🇮🇹",
    callingCode: "+39",
  },

  {
    code: "JPN",
    name: "Japan",
    nationality: "Japanese",
    flag: "🇯🇵",
    callingCode: "+81",
  },
  {
    code: "KEN",
    name: "Kenya",
    nationality: "Kenyan",
    flag: "🇰🇪",
    callingCode: "+254",
  },
  {
    code: "KOR",
    name: "South Korea",
    nationality: "South Korean",
    flag: "🇰🇷",
    callingCode: "+82",
  },

  {
    code: "MEX",
    name: "Mexico",
    nationality: "Mexican",
    flag: "🇲🇽",
    callingCode: "+52",
  },
  {
    code: "NLD",
    name: "Netherlands",
    nationality: "Dutch",
    flag: "🇳🇱",
    callingCode: "+31",
  },
  {
    code: "NGA",
    name: "Nigeria",
    nationality: "Nigerian",
    flag: "🇳🇬",
    callingCode: "+234",
  },
  {
    code: "NOR",
    name: "Norway",
    nationality: "Norwegian",
    flag: "🇳🇴",
    callingCode: "+47",
  },

  {
    code: "PAK",
    name: "Pakistan",
    nationality: "Pakistani",
    flag: "🇵🇰",
    callingCode: "+92",
  },
  {
    code: "PHL",
    name: "Philippines",
    nationality: "Filipino",
    flag: "🇵🇭",
    callingCode: "+63",
  },
  {
    code: "POL",
    name: "Poland",
    nationality: "Polish",
    flag: "🇵🇱",
    callingCode: "+48",
  },
  {
    code: "PRT",
    name: "Portugal",
    nationality: "Portuguese",
    flag: "🇵🇹",
    callingCode: "+351",
  },

  {
    code: "RUS",
    name: "Russia",
    nationality: "Russian",
    flag: "🇷🇺",
    callingCode: "+7",
  },
  {
    code: "SAU",
    name: "Saudi Arabia",
    nationality: "Saudi",
    flag: "🇸🇦",
    callingCode: "+966",
  },
  {
    code: "SGP",
    name: "Singapore",
    nationality: "Singaporean",
    flag: "🇸🇬",
    callingCode: "+65",
  },
  {
    code: "ZAF",
    name: "South Africa",
    nationality: "South African",
    flag: "🇿🇦",
    callingCode: "+27",
  },
  {
    code: "ESP",
    name: "Spain",
    nationality: "Spanish",
    flag: "🇪🇸",
    callingCode: "+34",
  },
  {
    code: "SWE",
    name: "Sweden",
    nationality: "Swedish",
    flag: "🇸🇪",
    callingCode: "+46",
  },
  {
    code: "CHE",
    name: "Switzerland",
    nationality: "Swiss",
    flag: "🇨🇭",
    callingCode: "+41",
  },

  {
    code: "THA",
    name: "Thailand",
    nationality: "Thai",
    flag: "🇹🇭",
    callingCode: "+66",
  },
  {
    code: "TUR",
    name: "Turkey",
    nationality: "Turkish",
    flag: "🇹🇷",
    callingCode: "+90",
  },

  {
    code: "UKR",
    name: "Ukraine",
    nationality: "Ukrainian",
    flag: "🇺🇦",
    callingCode: "+380",
  },
  {
    code: "GBR",
    name: "United Kingdom",
    nationality: "British",
    flag: "🇬🇧",
    callingCode: "+44",
  },
  {
    code: "USA",
    name: "United States",
    nationality: "American",
    flag: "🇺🇸",
    callingCode: "+1",
  },

  {
    code: "VNM",
    name: "Vietnam",
    nationality: "Vietnamese",
    flag: "🇻🇳",
    callingCode: "+84",
  },
  {
    code: "ZMB",
    name: "Zambia",
    nationality: "Zambian",
    flag: "🇿🇲",
    callingCode: "+260",
  },
  {
    code: "ZWE",
    name: "Zimbabwe",
    nationality: "Zimbabwean",
    flag: "🇿🇼",
    callingCode: "+263",
  },
];
